-- OLD TAGS
-- INSERT INTO tags (name) VALUES ('비즈니스');
-- INSERT INTO tags (name) VALUES ('일상 대화');
-- INSERT INTO tags (name) VALUES ('금융/경제');
-- INSERT INTO tags (name) VALUES ('IT/소프트웨어');
-- INSERT INTO tags (name) VALUES ('법률/특허/계약');
-- INSERT INTO tags (name) VALUES ('의학');
-- INSERT INTO tags (name) VALUES ('기타');
-- INSERT INTO tags (name) VALUES ('스포츠');
-- INSERT INTO tags (name) VALUES ('여행/쇼핑');
-- INSERT INTO tags (name) VALUES ('NIA_향토문화/음식');
-- INSERT INTO tags (name) VALUES ('NIA_축제/행사');
-- INSERT INTO tags (name) VALUES ('NIA_스포츠');
-- INSERT INTO tags (name) VALUES ('NIA_IT기술');
-- INSERT INTO tags (name) VALUES ('NIA_가정통신문');
-- INSERT INTO tags (name) VALUES ('NIA_금융/증시');
-- INSERT INTO tags (name) VALUES ('NIA_특허/기술');
-- INSERT INTO tags (name) VALUES ('NIA_KPOP/대중문화');
-- INSERT INTO tags (name) VALUES ('NIA_사회/노동/복지');
-- INSERT INTO tags (name) VALUES ('NIA_일상생활');
-- INSERT INTO tags (name) VALUES ('NIA_해외영업');
-- INSERT INTO tags (name) VALUES ('NIA_채팅');
-- INSERT INTO tags (name) VALUES ('예술/문화');
-- NEW TAGS
INSERT INTO tags (name) VALUES ('art');
INSERT INTO tags (name) VALUES ('beauty');
INSERT INTO tags (name) VALUES ('business');
INSERT INTO tags (name) VALUES ('commerce');
INSERT INTO tags (name) VALUES ('computer');
INSERT INTO tags (name) VALUES ('conversation');
INSERT INTO tags (name) VALUES ('customer service');
INSERT INTO tags (name) VALUES ('economy');
INSERT INTO tags (name) VALUES ('education');
INSERT INTO tags (name) VALUES ('engineering');
INSERT INTO tags (name) VALUES ('fashion');
INSERT INTO tags (name) VALUES ('financial');
INSERT INTO tags (name) VALUES ('information technology');
INSERT INTO tags (name) VALUES ('law');
INSERT INTO tags (name) VALUES ('legal');
INSERT INTO tags (name) VALUES ('literature');
INSERT INTO tags (name) VALUES ('liberal arts');
INSERT INTO tags (name) VALUES ('marketing');
INSERT INTO tags (name) VALUES ('medicine');
INSERT INTO tags (name) VALUES ('patent');
INSERT INTO tags (name) VALUES ('politics');
INSERT INTO tags (name) VALUES ('religion');
INSERT INTO tags (name) VALUES ('science');
INSERT INTO tags (name) VALUES ('shopping');
INSERT INTO tags (name) VALUES ('social media');
INSERT INTO tags (name) VALUES ('society');
INSERT INTO tags (name) VALUES ('sports');
INSERT INTO tags (name) VALUES ('technology');
INSERT INTO tags (name) VALUES ('transport');
INSERT INTO tags (name) VALUES ('travel');
