INSERT INTO partners (company, country) VALUES ('ETRI', 'Korea');
INSERT INTO partners (company, country) VALUES ('NAVER', 'Korea');
INSERT INTO partners (company, country) VALUES ('MEGADIC', 'Korea');
INSERT INTO partners (company, country) VALUES ('NTT Docomo', 'Japan');
INSERT INTO partners (company, country) VALUES ('SYSTRAN', 'Korea');
INSERT INTO partners (company, country) VALUES ('삼성종합기술원', 'Korea');
INSERT INTO partners (company, country) VALUES ('삼성전자', 'Korea');
INSERT INTO partners (company, country) VALUES ('BAIDU', 'China');
INSERT INTO partners (company, country) VALUES ('LOGBAR', 'Japan');
INSERT INTO partners (company, country) VALUES ('APPLE', 'United States');
INSERT INTO partners (company, country) VALUES ('CROSSLANGUAGE', 'Japan');
INSERT INTO partners (company, country) VALUES ('삼성SDS', 'Korea');
INSERT INTO partners (company, country) VALUES ('NIA', 'Korea');
INSERT INTO partners (company, country) VALUES ('KAKAO', 'Korea');
INSERT INTO partners (company, country) VALUES ('현대자동차', 'Korea');
INSERT INTO partners (company, country) VALUES ('EPOPSOFT', 'Korea');
INSERT INTO partners (company, country) VALUES ('GOOGLE', 'United States');
INSERT INTO partners (company, country) VALUES ('TRIDENT', 'United States');
INSERT INTO partners (company, country) VALUES ('BYTEDANCE', 'China');
INSERT INTO partners (company, country) VALUES ('UPTEMPO', 'Korea');
INSERT INTO partners (company, country) VALUES ('NGOHUNG', 'Vietnam');
INSERT INTO partners (company, country) VALUES ('MICROSOFT', 'United States');
INSERT INTO partners (company, country) VALUES ('TOPPANPRINTING', 'Japan');
INSERT INTO partners (company, country) VALUES ('FLITTO', 'Korea');
INSERT INTO partners (company, country) VALUES ('아주뉴스', 'Korea');
INSERT INTO partners (company, country) VALUES ('국립국어원', 'Korea');
