INSERT INTO projects (partner_id, title) VALUES (1, '2014_ETRI_중일한');
INSERT INTO projects (partner_id, title) VALUES (2, '2014_NAVER_영인');
INSERT INTO projects (partner_id, title) VALUES (2, '2014_NAVER_영태');
INSERT INTO projects (partner_id, title) VALUES (1, '2014_ETRI_중영일한');
INSERT INTO projects (partner_id, title) VALUES (1, '2014_ETRI_영프스');
INSERT INTO projects (partner_id, title, description) VALUES (3, '2015_MEGADIC_중영한', '구입');
INSERT INTO projects (partner_id, title) VALUES (1, '2015_ETRI_영프스');
INSERT INTO projects (partner_id, title) VALUES (1, '2016_ETRI_아중영프독일한러스');
INSERT INTO projects (partner_id, title) VALUES (4, '2016_NTT_중영인일한');
INSERT INTO projects (partner_id, title) VALUES (2, '2016_NAVER_영인');
INSERT INTO projects (partner_id, title) VALUES (5, '2016_SYSTRAN_영독러');
INSERT INTO projects (partner_id, title) VALUES (4, '2016_NTT_중영일한');
INSERT INTO projects (partner_id, title) VALUES (5, '2016_SYSTRAN_영한');
INSERT INTO projects (partner_id, title) VALUES (4, '2016_NTT_중일한');
INSERT INTO projects (partner_id, title) VALUES (5, '2016_SYSTRAN_중일한');
INSERT INTO projects (partner_id, title) VALUES (5, '2016_SYSTRAN_중영프일한스');
INSERT INTO projects (partner_id, title) VALUES (4, '2016_NTT_중영일한');
INSERT INTO projects (partner_id, title) VALUES (4, '2017_NTT_중일한');
INSERT INTO projects (partner_id, title) VALUES (1, '2017_ETRI_영독프러스');
INSERT INTO projects (partner_id, title) VALUES (6, '2017_삼성종합기술원_중한');
INSERT INTO projects (partner_id, title) VALUES (7, '2017_삼성전자_영한');
INSERT INTO projects (partner_id, title) VALUES (1, '2017_ETRI_아중영일한');
INSERT INTO projects (partner_id, title) VALUES (1, '2017_ETRI_영한');
INSERT INTO projects (partner_id, title) VALUES (4, '2017_NTT_중영일한');
INSERT INTO projects (partner_id, title) VALUES (1, '2017_ETRI_아중영프독일한러스');
INSERT INTO projects (partner_id, title) VALUES (8, '2017_BAIDU_중일');
INSERT INTO projects (partner_id, title) VALUES (9, '2018_LOGBAR_중일');
INSERT INTO projects (partner_id, title) VALUES (10, '2018_APPLE_영일한');
INSERT INTO projects (partner_id, title) VALUES (4, '2018_NTT_중영일한');
INSERT INTO projects (partner_id, title) VALUES (9, '2018_LOGBAR_중일한');
INSERT INTO projects (partner_id, title) VALUES (11, '2018_CROSSLANGUAGE_영일');
INSERT INTO projects (partner_id, title) VALUES (10, '2018_APPLE_아중영일한러');
INSERT INTO projects (partner_id, title) VALUES (12, '2018_삼성SDS_영한');
INSERT INTO projects (partner_id, title) VALUES (13, '2018_NIA_아영인말태베');
INSERT INTO projects (partner_id, title) VALUES (1, '2018_ETRI_중영러베');
INSERT INTO projects (partner_id, title) VALUES (14, '2018_KAKAO_아인한');
INSERT INTO projects (partner_id, title) VALUES (8, '2018_BAIDU_독러영중태');
INSERT INTO projects (partner_id, title) VALUES (4, '2018_NTT_중영일한');
INSERT INTO projects (partner_id, title) VALUES (15, '2019_현대자동차_영한');
INSERT INTO projects (partner_id, title) VALUES (1, '2019_ETRI_아영인말태베');
INSERT INTO projects (partner_id, title) VALUES (16, '2019_EPOPSOFT_영한');
INSERT INTO projects (partner_id, title) VALUES (4, '2019_NTT_중영일한');
INSERT INTO projects (partner_id, title) VALUES (4, '2019_NTT_중일');
INSERT INTO projects (partner_id, title) VALUES (17, '2019_GOOGLE_중영인일베');
INSERT INTO projects (partner_id, title) VALUES (10, '2019_APPLE_중영일한');
INSERT INTO projects (partner_id, title) VALUES (17, '2019_GOOGLE_아중영프독인포스러베_SAMPLE');
INSERT INTO projects (partner_id, title) VALUES (18, '2019_TRIDENT_영인한태타터베_SAMPLE');
INSERT INTO projects (partner_id, title) VALUES (19, '2019_BYTEDANCE_중일');
INSERT INTO projects (partner_id, title) VALUES (13, '2019_NIA_영한_대화');
INSERT INTO projects (partner_id, title) VALUES (13, '2019_NIA_영한_뉴스');
INSERT INTO projects (partner_id, title) VALUES (13, '2019_NIA_영한_구어체');
INSERT INTO projects (partner_id, title, description) VALUES (3, '2020_MEGADIC_영프', '구입');
INSERT INTO projects (partner_id, title, description) VALUES (21, '2020_NGOHUNG_영베', '구입');
INSERT INTO projects (partner_id, title) VALUES (22, '2020_MICROSOFT_14개언어');
INSERT INTO projects (partner_id, title, description) VALUES (23, '2020_TOPPANPRINTING_네영일', '구입');
INSERT INTO projects (partner_id, title, description) VALUES (24, '2020_FLITTO_다수언어', '자체구축');
INSERT INTO projects (partner_id, title, description) VALUES (25, '2020_아주뉴스_영한', '구입');
INSERT INTO projects (partner_id, title, description) VALUES (13, '2020_NIA_한영', '신문기사/문어체');
INSERT INTO projects (partner_id, title, description) VALUES (13, '2020_NIA_한일중', '신문기사/문어체');
INSERT INTO projects (partner_id, title) VALUES (13, '2021_NIA_독스일중프한');
INSERT INTO projects (partner_id, title, description) VALUES (13, '2020_NIA_한영', 'TWIGFARM 구축');
INSERT INTO projects (partner_id, title, description) VALUES (2, 'NAVER_오픈사전', 'NAVER 오픈사전 크롤링');
INSERT INTO projects (partner_id, title) VALUES (26, '2021_국립국어원');
INSERT INTO projects (partner_id, title) VALUES (24, '집단지성요청');
INSERT INTO projects (partner_id, title) VALUES (24, 'Local Project Manager');
INSERT INTO projects (partner_id, title) VALUES (2, '2022_NAVER_다국어');
INSERT INTO projects (partner_id, title) VALUES (7, '2020_삼성전자_4병렬코퍼스');
